### PR TITLE
Rio homepage revamp

### PR DESCRIPTION
**Pull request by keepitrio**
@bbensch09 

The only problem I had was that maybe the database wasn't populated correctly with the seed file and I couldn't see any prices on the pricing page. I see "Pricing not yet available"

I definitely still want to change up everything below the top section but I'm not entirely sure how. Let me know what you think!

### CODE REVIEW

**Comment by bbensch09** [comment]
Hi @keepitrio -- Sorry for the delayed reply, but I like it! definitely a great start.

I just just added some instructions to the read me and fixed the seed file so it should work as would be expected. will also send you the two CSV files you need to load such that prices and locations appear as they should. Other quick notes:
- Really like the above the fold, but the bottom sections could still use some work. 
- font size feels a little small, but generally like the amount of white/open space.
- i really don't like the current side by side boxes for search by location vs. apply today with "compare lesson prices" and "shop season passes" above each box. but this is admittedly WIP.
screen shot 2017-11-30 at 11 38 40 pm

Let me know if you have any other questions, but in general love the approach so far and am excited to see you do to the rest of the page what you've done for the above the fold part.
-Brian

**Comment by bbensch09** [comment]
Here are the two CSV files you'll want to upload when setting up the DB.
upload these before running rails db:seed.

ᐧ

**Comment by keepitrio** [comment]
@bbensch09 Thanks for the feedback! I'm not seeing the 2 csv files, would you be able to email them to me or send them on FB messenger? Thank you!

**Comment by bbensch09** [comment]
Hi @keepitrio -- should have thought of this before as well, but I have a demo.snowschoolers.com domain setup, and so just configured Heroku to automatically deploy updates from your rio-homepage-revamp branch, so if you have any other issues with the DB setup, you can also just push up a new version, give Heroku a few minutes, and then you'll be able to see it live there. Obviously not great for real-time work, but better than nothing. And also let's me share version with business partner to get their feedback ;-)

**Pull request closed without merging**
